name: powersync
version: 0.2.0-preview.1
homepage: https://powersync.co
description: PowerSync Flutter SDK - keep PostgreSQL databases in sync with on-device SQLite databases.
environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  # Needed because of sqlite3_flutter_libs
  flutter:
    sdk: flutter

  sqlite3: ^1.9.1
  sqlite3_flutter_libs: ^0.5.12
  http: ^0.13.5
  uuid: ^3.0.7
  async: ^2.10.0
  logging: ^1.1.1
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  test_api: ^0.4.18
  path_provider: ^2.0.13

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
