name: powersync
version: 0.1.1-preview.2
homepage: https://powersync.co
description: PowerSync Flutter SDK - keep PostgreSQL databases in sync with on-device SQLite databases.
environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  # Needed because of sqlite3_flutter_libs
  flutter:
    sdk: flutter

  sqlite3: ^1.9.1
  sqlite3_flutter_libs: ^0.5.12
  http: ^0.13.5
  uuid: ^3.0.7
  async: ^2.10.0
  logging: ^1.1.1
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
