name: powersync
version: 0.1.0-preview6
publish_to: https://onepub.dev/api/aavdavuhno/
homepage: https://powersync.co
description: PowerSync Dart/Flutter SDK
environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  sqlite3: ^1.9.1
  sqlite3_flutter_libs: ^0.5.12
  http: ^0.13.5
  uuid: ^3.0.7
  async: ^2.10.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
