name: Publish packages
on:
  push:
    tags:
      - "powersync-v[0-9]+.[0-9]+.[0-9]+"
      - "powersync_attachments_helper-v[0-9]+.[0-9]+.[0-9]+"
      - "powersync_flutter_libs-v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  publish-packages:
    name: Publish packages
    permissions:
      contents: write
      id-token: write # Required for authentication using OIDC
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1 # Creates and configures token for publishing

      - name: Install melos
        run: dart pub global activate melos

      - name: Publish packages dry run
        run: |
          melos publish

      # - name: Publish packages
      #   run: |
      #     melos publish --no-dry-run
