name: Publish packages
on:
  push:
    tags:
      - "powersync-v[0-9]+.[0-9]+.[0-9]+"
      - "powersync_attachments_helper-v[0-9]+.[0-9]+.[0-9]+*"
      - "powersync_flutter_libs-v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish-packages:
    name: Publish packages
    permissions:
      contents: write
      id-token: write # Required for authentication using OIDC
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1 # Creates and configures token for publishing

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Install melos
        run: flutter pub global activate melos

      - name: Install dependencies
        run: melos bootstrap

      - name: Set powersync core version
        run: echo "CORE_VERSION=v0.1.8" >> $GITHUB_ENV

      - name: Publish packages dry run
        run: |
          melos publish --yes

      - name: Publish packages
        run: |
          melos publish --no-dry-run --yes
