# This triggers whenever a tagged release is pushed
name: Compile Assets and Create Draft Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags beginning with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Install Dependencies and Compile Assets
        run: melos prepare

      - name: Create Draft Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: true # TODO update when out of alpha
          draft: true
          files: |
            assets/powersync_db.worker.js
